# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MakeADish' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MakeADish
  pod 'SwiftLint', '~> 0.27'

  target 'MakeADishTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MakeADishUITests' do
    # Pods for testing
  end

end
